### ISSUE TITLE
Google indexing

### ISSUE THREAD

**Issue by anonrig** [prerender/prerender-node#100]
I've been using Google Search Console and tried to index website as Google by their platform. Unfortunately, even though I've been using `prerender-node` the website scraped by Google was the non-javascript version and therefore I believe that `prerender-node` fails to identify GoogleBots.

**Comment by thoop** [comment]
If you were using "Fetch as Google", there is a known bug where Fetch as Google does not automatically check for the fragment meta tag and add the `?_escaped_fragment_=` query parameter to the URL. Googlebot does correctly support the escaped fragment crawling protocol though. When using Fetch as Google, you should manually enter the ?_escaped_fragment_= URL.

**Comment by danielparas** [comment]
having problems with indexing too + looking at cached version from search results page shows the non-javascript version :/ but when testing manually with ?_escaped_fragment_= loads the prerendered version. According to this [google announcement ](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html) escaped_fragment crawling is deprecated as of oct 2015.

**Comment by thoop** [comment]
Google still crawls using the escaped fragment crawling protocol. We've found that when Google is required to execute your javascript, their crawl speed slows way down since they have to wait for your pages to load now. Serving prerendered pages to Google is still recommended in order to have them crawl your website quickly and get more of your URLs into their index.

http://searchengineland.com/can-now-trust-google-crawl-ajax-sites-235267

Send me an email at todd@prerender.io and I'd love to look into the issues that you're seeing on your site. Happy to help get things 100%!

**Comment by danielparas** [comment]
Thanks @thoop for the reply - we spoke over email and as you indicated it seems I was missing the 
`<meta name="fragment" content="!">` in the `head` of my pages. Now just need to wait and see the result :)

Mentioning it here for anyone with similar problems in the future. 

Thanks again!

**Comment by thoop** [comment]
Sure thing!
