### ISSUE TITLE
Doesn't work for twitter

### ISSUE THREAD

**Issue by yantakus** [prerender/prerender-node#161]
We are using `prerender-node` for our website lift.co and it works just fine for Facebook. You can try sharing a blog post, let's say https://lift.co/magazine/cannabis-jobs-canada-industry and here's what you see:

![image](https://user-images.githubusercontent.com/2179726/43646216-f077dffe-973c-11e8-9488-5fc2f690deeb.png)

As you can see facebook is able to recognize all the meta tags: `og:image`, `og:description`, etc.

But it doesn't work for twitter. When trying to share the same post here's what we can see:

![image](https://user-images.githubusercontent.com/2179726/43646282-2892511c-973d-11e8-9bb2-3bd9d88378f6.png)

Also [twitter card validator](https://cards-dev.twitter.com/validator) can only find `twitter:card` tag which is hard-coded in our index.html file and is available without running javascript:

![image](https://user-images.githubusercontent.com/2179726/43646424-93eee5b0-973d-11e8-8a74-7050970febf8.png)

Any ideas on why it happens and suggestions on how to debug it? Thanks in advance.

**Comment by thoop** [comment]
That card validator looks correct and I'm seeing the prerendered page when I change my user agent to `twitterbot` and view that URL. I think the image isn't displaying on that card validator because you have:
```
<meta name="twitter:image" content="//images.ctfassets.net/i39s3xee28h4/1BxBxNoRWQ88YsM2ge4wo6/0d12b61c99097298de1131196cd255a2/cannabis-jobs-canada.jpg" data-react-helmet="true">
```
I'm not sure if twitter knows how to handle // URLs like that? I could be wrong.

And it looks like the twitter share popup is just setting the "text" property in that URL instead of fetching the data for a card.

So it seems like you're serving back a prerendered page when the user agent is twitterbot.

**Comment by thoop** [comment]
Feel free to reopen if you are still having issues here but from my test it looked like the prerendered page was being served back.

**Comment by yantakus** [comment]
@thoop sorry, I forgot to answer. You were right, the problem was with missing protocol in image url. Thanks for the help!

**Comment by thoop** [comment]
Great!
