### ISSUE TITLE
Shouldn't buildApiUrl use req.originalUrl inseated of req.url ?

### ISSUE THREAD

**Issue by redben** [prerender/prerender-node#39]
In case you have a middleware that does some url rewrite/alias and overwrites req.url,  express keeps a copy of the original url in req.originalUrl.

It would be good if prerender-node used that value instead of req.url.

see https://github.com/prerender/prerender-node/blob/master/index.js#L211

Example : 
- ``GET /my-nice-angular-app-url?_escaped_fragment_=val``
- Some middleware rewrites it to ``/some/thing/else?_escaped_fragment_=val``
- prerender should request  ``/my-nice-angular-app-url?_escaped_fragment_=val``

**Comment by homeyer** [comment]
prerender-node no longer depends on express (although we have integration tests for Express3 and 4). This is to support other node web frameworks, like meteor. Closing this since it would re-introduce that dependency. 

The appropriate work around would be to include the prerender middleware higher in the request chain.
