### ISSUE TITLE
Suggestion for documentation and better error reporting

### ISSUE THREAD

**Issue by erikverheij** [prerender/prerender-node#87]
Hi there,

I've spent some time getting the middleware to work. In the end it appeared that my apache config with virtual hosts caused the problem. Somehow the request hostname is set to the local hostname. 

Setting the host name manually solved the problem.

```
require('prerender-node').set('host', 'my-website.com');
```

It might be valuable for others to have this in the docs.

It took me quite a while to find out this was the problem. The prerender.io service only responds with; `504 Gateway Time-out`. I think the prerender.io service should provide a more detailed response e.g.;

```
Could not render page at http://localhost:3010/app-path/.

```

**Comment by thoop** [comment]
Thanks! I'll definitely add `host` to the docs. Sorry that wasn't already there.

As for the 504, that might be something we could add to the website? I would hate to return any content since we try not to change the responses that we send as much as possible. But I do see that this is a case where that might be necessary.

**Comment by erikverheij** [comment]
Sounds good!

I can see the point of not returning any content. Perhaps something less invasive for the backlog; 

You could implement some debugging library like [visionmedia's debug](https://github.com/visionmedia/debug). Debug messages would then provide more detailed info about the request and response. I had to modify the module manually to console.log the request to get a clue about what was going on. Since you can not fully test it in a dev environment it is quite annoying to debug like this.

**Comment by thoop** [comment]
We do have our open source prerender server which lets you fully test in a dev environment: https://github.com/prerender/prerender

This problem wouldn't have been caught though since it would work locally but not in production with how your site is set up with the localhost URL. Did you check your crawl stats on prerender.io at all during the process and see the localhost URLs? I wonder if we could just display something there if we detect a localhost URL to warn you that they aren't going to work.

**Comment by erikverheij** [comment]
Hmm, yes it did show up there. Although I thought these requests came from
my fellow developer trying things locally.

Showing a warning there would definitely be helpful. Perhaps you can how
many users are trying to render localhost urls. I wouldn't be surprised if
it's a lot :)



2015-11-04 19:33 GMT+01:00 Todd Hooper <notifications@github.com>:

**Comment by thoop** [comment]
added documentation for `host` param!
